<a href="https://colab.research.google.com/github/NagaramTarun/python/blob/main/day14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = sns.load_dataset('taxis')

In [3]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](2), float64(5), int64(1), object(6)
memory usage: 703.7+ KB

In [5]:
df.sample(15)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
5804,2019-03-08 17:57:46,2019-03-08 18:04:33,1,1.04,6.00,0.00,0.00,7.80,green,cash,Astoria,Astoria,Queens,Queens
2395,2019-03-20 18:18:45,2019-03-20 18:20:29,2,0.39,3.50,1.00,0.00,8.80,yellow,credit card,Upper West Side South,Upper West Side South,Manhattan,Manhattan
4425,2019-03-13 16:11:08,2019-03-13 16:27:08,1,2.09,12.00,4.08,0.00,20.38,yellow,credit card,Yorkville West,Upper West Side South,Manhattan,Manhattan
547,2019-03-19 11:44:37,2019-03-19 12:05:39,1,2.52,14.50,0.00,0.00,17.80,yellow,cash,Times Sq/Theatre District,West Village,Manhattan,Manhattan
1005,2019-03-01 21:12:39,2019-03-01 21:16:16,1,0.61,4.50,0.00,0.00,8.30,yellow,cash,Union Sq,Murray Hill,Manhattan,Manhattan
3336,2019-03-06 09:24:48,2019-03-06 09:25:07,1,1.70,14.00,2.00,0.00,16.30,yellow,credit card,Midtown North,Midtown North,Manhattan,Manhattan
5752,2019-03-24 09:35:57,2019-03-24 09:42:13,1,1.30,7.00,0.00,0.00,7.80,green,credit card,Stuyvesant Heights,East Williamsburg,Brooklyn,Brooklyn
466,2019-03-07 09:09:24,2019-03-07 09:48:44,3,8.19,30.50,0.00,5.76,39.56,yellow,cash,East Chelsea,Park Slope,Manhattan,Brooklyn
6251,2019-03-14 20:04:50,2019-03-14 20:13:47,1,1.90,8.50,2.50,0.00,15.05,green,credit card,East Harlem North,Upper East Side North,Manhattan,Manhattan
5467,2019-03-14 09:14:28,2019-03-14 09:39:12,1,4.47,16.39,0.00,0.00,16.89,green,credit card,East New York,Bedford,Brooklyn,Brooklyn
4446,2019-03-30 11:00:44,2019-03-30 11:16:46,1,2.20,12.00,3.05,0.00,18.35,yellow,credit card,Yorkville East,Midtown Center,Manhattan,Manhattan
2192,2019-03-27 22:44:10,2019-03-27 22:49:18,1,1.13,6.00,1.50,0.00,11.30,yellow,credit card,Clinton East,West Chelsea/Hudson Yards,Manhattan,Manhattan
3856,2019-03-05 10:54:33,2019-03-05 11:08:08,2,1.98,11.00,2.86,0.00,17.16,yellow,credit card,Lenox Hill East,Sutton Place/Turtle Bay North,Manhattan,Manhattan
6023,2019-03-13 00:25:25,2019-03-13 00:33:07,1,1.20,7.00,0.00,0.00,8.30,green,cash,Jackson Heights,Elmhurst,Queens,Queens
3237,2019-03-30 23:13:30,2019-03-30 23:33:39,2,2.39,14.00,0.00,0.00,17.80,yellow,cash,SoHo,Murray Hill,Manhattan,Manhattan

In [6]:
df.head(30)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.00,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.00,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.00,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.00,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.00,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
5,2019-03-11 10:37:23,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.00,12.96,yellow,credit card,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan
6,2019-03-26 21:07:31,2019-03-26 21:17:29,1,3.65,13.0,2.00,0.00,18.80,yellow,credit card,Battery Park City,Two Bridges/Seward Park,Manhattan,Manhattan
7,2019-03-22 12:47:13,2019-03-22 12:58:17,0,1.40,8.5,0.00,0.00,11.80,yellow,NaN,Murray Hill,Flatiron,Manhattan,Manhattan
8,2019-03-23 11:48:50,2019-03-23 12:06:14,1,3.63,15.0,1.00,0.00,19.30,yellow,credit card,East Harlem South,Midtown Center,Manhattan,Manhattan
9,2019-03-08 16:18:37,2019-03-08 16:26:57,1,1.52,8.0,1.00,0.00,13.30,yellow,credit card,Lincoln Square East,Central Park,Manhattan,Manhattan
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.0,0.00,0.00,17.80,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
11,2019-03-20 19:39:42,2019-03-20 19:45:36,1,1.53,6.5,2.16,0.00,12.96,yellow,credit card,Upper West Side South,Manhattan Valley,Manhattan,Manhattan
12,2019-03-18 21:27:14,2019-03-18 21:34:16,1,1.05,6.5,1.00,0.00,11.30,yellow,credit card,Murray Hill,Midtown Center,Manhattan,Manhattan
13,2019-03-19 07:55:25,2019-03-19 08:09:17,1,1.75,10.5,0.00,0.00,13.80,yellow,cash,Lincoln Square West,Times Sq/Theatre District,Manhattan,Manhattan
14,2019-03-27 12:13:34,2019-03-27 12:25:48,0,2.90,11.5,0.00,0.00,14.80,yellow,cash,Financial District North,Two Bridges/Seward Park,Manhattan,Manhattan
15,2019-03-16 17:53:34,2019-03-16 18:13:57,3,2.09,13.5,0.00,0.00,16.80,yellow,cash,Upper West Side North,Clinton East,Manhattan,Manhattan
16,2019-03-15 12:36:05,2019-03-15 12:54:28,1,2.12,13.0,0.00,0.00,16.30,yellow,cash,East Chelsea,Meatpacking/West Village West,Manhattan,Manhattan
17,2019-03-23 20:50:49,2019-03-23 21:02:07,1,2.60,10.5,2.00,0.00,16.30,yellow,credit card,Midtown Center,East Harlem South,Manhattan,Manhattan
18,2019-03-27 06:28:36,2019-03-27 06:38:10,1,2.18,9.5,1.92,0.00,14.72,yellow,credit card,Gramercy,Midtown Center,Manhattan,Manhattan
19,2019-03-25 22:04:25,2019-03-25 22:11:30,6,1.08,6.5,1.08,0.00,11.38,yellow,credit card,East Chelsea,East Chelsea,Manhattan,Manhattan
20,2019-03-21 03:37:34,2019-03-21 03:44:13,1,1.07,6.5,1.54,0.00,11.84,yellow,credit card,Penn Station/Madison Sq West,Kips Bay,Manhattan,Manhattan
21,2019-03-25 23:05:54,2019-03-25 23:11:13,1,0.80,5.5,2.30,0.00,11.60,yellow,credit card,Penn Station/Madison Sq West,Murray Hill,Manhattan,Manhattan
22,2019-03-28 17:20:54,2019-03-28 17:55:57,1,9.82,31.5,8.31,5.76,49.87,yellow,credit card,LaGuardia Airport,Sutton Place/Turtle Bay North,Queens,Manhattan
23,2019-03-04 12:15:39,2019-03-04 12:26:53,5,1.09,8.5,2.36,0.00,14.16,yellow,credit card,Sutton Place/Turtle Bay North,Midtown North,Manhattan,Manhattan
24,2019-03-24 09:53:28,2019-03-24 10:01:22,5,2.89,9.5,3.84,0.00,16.64,yellow,credit card,Lenox Hill West,Gramercy,Manhattan,Manhattan
25,2019-03-25 08:01:01,2019-03-25 08:13:27,1,1.90,10.0,3.00,0.00,16.30,yellow,credit card,Lincoln Square East,Midtown South,Manhattan,Manhattan
26,2019-03-03 02:45:36,2019-03-03 03:02:14,1,3.35,13.5,0.00,0.00,17.30,yellow,cash,West Chelsea/Hudson Yards,Seaport,Manhattan,Manhattan
27,2019-03-16 20:30:36,2019-03-16 20:46:22,1,2.60,12.5,3.26,0.00,19.56,yellow,credit card,Clinton East,Lenox Hill West,Manhattan,Manhattan
28,2019-03-20 12:25:31,2019-03-20 12:45:02,1,4.71,17.5,0.00,0.00,18.30,yellow,credit card,Clinton West,East Harlem North,Manhattan,Manhattan
29,2019-03-06 08:09:03,2019-03-06 08:27:11,1,0.92,12.0,0.00,0.00,15.30,yellow,cash,UN/Turtle Bay South,Garment District,Manhattan,Manhattan

In [7]:
df.tail(10)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
6423,2019-03-12 08:10:47,2019-03-12 08:35:35,1,4.30,18.50,0.00,0.0,19.30,green,credit card,Saint Albans,Hillcrest/Pomonok,Queens,Queens
6424,2019-03-30 20:52:15,2019-03-30 20:59:55,1,1.70,8.00,0.00,0.0,9.30,green,cash,Central Harlem,Central Harlem North,Manhattan,Manhattan
6425,2019-03-07 15:34:30,2019-03-07 16:31:06,1,9.12,26.32,0.00,0.0,26.82,green,credit card,Park Slope,East New York,Brooklyn,Brooklyn
6426,2019-03-28 08:04:47,2019-03-28 08:07:46,1,0.71,4.50,0.50,0.0,5.80,green,credit card,Central Park,Upper West Side North,Manhattan,Manhattan
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.00,0.00,0.0,20.00,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.50,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.00,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.00,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.00,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.00,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [8]:
df['color']

0       yellow
1       yellow
2       yellow
3       yellow
4       yellow
         ...
6428     green
6429     green
6430     green
6431     green
6432     green
Name: color, Length: 6433, dtype: object

In [9]:
df['color'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
6428    False
6429    False
6430    False
6431    False
6432    False
Name: color, Length: 6433, dtype: bool

In [10]:
df['color'].isnull().sum()

0

In [11]:
df['payment'].isnull().sum()

44

In [12]:
df.isnull().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

In [13]:
df.shape[0]

6433

In [14]:
(df.isnull().sum()/df.shape[0])*100

pickup             0.000000
dropoff            0.000000
passengers         0.000000
distance           0.000000
fare               0.000000
tip                0.000000
tolls              0.000000
total              0.000000
color              0.000000
payment            0.683973
pickup_zone        0.404166
dropoff_zone       0.699518
pickup_borough     0.404166
dropoff_borough    0.699518
dtype: float64

# **Missing data handling**

1) imputation (fill in the blanks)
  
    1)stastical measures


    2)parameter

2)delete data
    
    row
    
    columns

In [15]:
df.drop('pickup_zone',axis=1)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Windsor Terrace,Brooklyn,Brooklyn

In [16]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [17]:
df.drop('pickup_zone',axis=1,inplace=True)

In [18]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Windsor Terrace,Brooklyn,Brooklyn

In [19]:
df.drop(['pickup','color','payment','total'],axis=1)

,dropoff,passengers,distance,fare,tip,tolls,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,West Village,Manhattan,Manhattan
3,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,Windsor Terrace,Brooklyn,Brooklyn

In [20]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Windsor Terrace,Brooklyn,Brooklyn

In [21]:
a = np.random.randint(10,50,15)

In [22]:
a

array([49, 19, 20, 14, 26, 26, 47, 17, 40, 26, 20, 20, 47, 34, 27])

In [23]:
a[a>40]

array([49, 47, 47])

In [24]:
df.iloc[455]

pickup                   2019-03-03 09:25:55
dropoff                  2019-03-03 09:34:53
passengers                                 1
distance                                1.78
fare                                     8.5
tip                                      1.5
tolls                                    0.0
total                                   13.3
color                                 yellow
payment                          credit card
dropoff_zone       West Chelsea/Hudson Yards
pickup_borough                     Manhattan
dropoff_borough                    Manhattan
Name: 455, dtype: object

In [25]:
df = sns.load_dataset('taxis')

In [26]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [28]:
df[df['color']=='yellow']

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5446,2019-03-11 21:19:42,2019-03-11 21:29:23,1,2.09,9.5,2.66,0.0,15.96,yellow,credit card,Battery Park City,Financial District North,Manhattan,Manhattan
5447,2019-03-20 18:09:46,2019-03-20 18:16:52,1,1.52,7.5,2.36,0.0,14.16,yellow,credit card,Upper West Side South,Upper East Side North,Manhattan,Manhattan
5448,2019-03-09 11:08:09,2019-03-09 11:18:03,1,2.05,9.5,2.56,0.0,15.36,yellow,credit card,Lenox Hill West,Upper West Side South,Manhattan,Manhattan
5449,2019-03-22 18:12:50,2019-03-22 18:22:05,1,1.07,7.5,2.36,0.0,14.16,yellow,credit card,West Village,Penn Station/Madison Sq West,Manhattan,Manhattan
5450,2019-03-07 18:02:33,2019-03-07 18:13:32,1,1.80,9.0,1.33,0.0,14.63,yellow,credit card,Lincoln Square East,Upper West Side North,Manhattan,Manhattan

In [30]:
df[df['total']> 15]

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.00,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
6,2019-03-26 21:07:31,2019-03-26 21:17:29,1,3.65,13.00,2.00,0.0,18.80,yellow,credit card,Battery Park City,Two Bridges/Seward Park,Manhattan,Manhattan
8,2019-03-23 11:48:50,2019-03-23 12:06:14,1,3.63,15.00,1.00,0.0,19.30,yellow,credit card,East Harlem South,Midtown Center,Manhattan,Manhattan
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.00,0.00,0.0,17.80,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
15,2019-03-16 17:53:34,2019-03-16 18:13:57,3,2.09,13.50,0.00,0.0,16.80,yellow,cash,Upper West Side North,Clinton East,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6425,2019-03-07 15:34:30,2019-03-07 16:31:06,1,9.12,26.32,0.00,0.0,26.82,green,credit card,Park Slope,East New York,Brooklyn,Brooklyn
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.00,0.00,0.0,20.00,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.00,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.00,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.00,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [31]:
df[df['payment']=='cash']

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.0,0.0,9.3,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.0,0.0,0.0,17.8,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
13,2019-03-19 07:55:25,2019-03-19 08:09:17,1,1.75,10.5,0.0,0.0,13.8,yellow,cash,Lincoln Square West,Times Sq/Theatre District,Manhattan,Manhattan
14,2019-03-27 12:13:34,2019-03-27 12:25:48,0,2.90,11.5,0.0,0.0,14.8,yellow,cash,Financial District North,Two Bridges/Seward Park,Manhattan,Manhattan
15,2019-03-16 17:53:34,2019-03-16 18:13:57,3,2.09,13.5,0.0,0.0,16.8,yellow,cash,Upper West Side North,Clinton East,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6420,2019-03-16 15:39:23,2019-03-16 15:46:18,2,1.20,7.0,0.0,0.0,7.8,green,cash,Central Harlem,Upper West Side North,Manhattan,Manhattan
6422,2019-03-22 20:17:35,2019-03-22 20:36:07,1,4.02,16.0,0.0,0.0,17.3,green,cash,Washington Heights South,Spuyten Duyvil/Kingsbridge,Manhattan,Bronx
6424,2019-03-30 20:52:15,2019-03-30 20:59:55,1,1.70,8.0,0.0,0.0,9.3,green,cash,Central Harlem,Central Harlem North,Manhattan,Manhattan
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.0,0.0,0.0,20.0,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.0,0.0,17.3,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn

In [32]:
df['payment']=='cash'

0       False
1        True
2       False
3       False
4       False
        ...
6428    False
6429    False
6430     True
6431    False
6432    False
Name: payment, Length: 6433, dtype: bool

In [35]:
df[(df['payment']=='cash') & (df['total']>15)]

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.0,0.0,0.0,17.80,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
15,2019-03-16 17:53:34,2019-03-16 18:13:57,3,2.09,13.5,0.0,0.0,16.80,yellow,cash,Upper West Side North,Clinton East,Manhattan,Manhattan
16,2019-03-15 12:36:05,2019-03-15 12:54:28,1,2.12,13.0,0.0,0.0,16.30,yellow,cash,East Chelsea,Meatpacking/West Village West,Manhattan,Manhattan
26,2019-03-03 02:45:36,2019-03-03 03:02:14,1,3.35,13.5,0.0,0.0,17.30,yellow,cash,West Chelsea/Hudson Yards,Seaport,Manhattan,Manhattan
29,2019-03-06 08:09:03,2019-03-06 08:27:11,1,0.92,12.0,0.0,0.0,15.30,yellow,cash,UN/Turtle Bay South,Garment District,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6407,2019-03-07 16:35:42,2019-03-07 16:50:03,1,2.68,12.0,0.0,0.0,16.55,green,cash,Morningside Heights,Upper East Side North,Manhattan,Manhattan
6408,2019-03-04 07:27:58,2019-03-04 07:49:25,1,6.48,22.0,0.0,0.0,25.55,green,cash,East Harlem North,Clinton East,Manhattan,Manhattan
6422,2019-03-22 20:17:35,2019-03-22 20:36:07,1,4.02,16.0,0.0,0.0,17.30,green,cash,Washington Heights South,Spuyten Duyvil/Kingsbridge,Manhattan,Bronx
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.0,0.0,0.0,20.00,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.0,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn