<a href="https://colab.research.google.com/github/NagaramTarun/python/blob/main/Day13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
import numpy as np
import seaborn as sns

In [31]:
k=[4,2.56789,9,87.9999,40,'hyderabad']
k

[4, 2.56789, 9, 87.9999, 40, 'hyderabad']

In [32]:
pd.Series(k)

0            4
1      2.56789
2            9
3      87.9999
4           40
5    hyderabad
dtype: object

In [33]:
a = np.random.randint(20,50,15)
a

array([22, 46, 30, 31, 22, 29, 46, 26, 44, 22, 26, 30, 20, 31, 41])

In [34]:
pd.Series(a)

0     22
1     46
2     30
3     31
4     22
5     29
6     46
7     26
8     44
9     22
10    26
11    30
12    20
13    31
14    41
dtype: int64

In [35]:
np.random.seed(34)
b = np.random.randint(100,200,(6,5))
b

array([[133, 185, 168, 135, 169],
       [111, 178, 129, 118, 129],
       [189, 129, 120, 196, 162],
       [105, 120, 151, 119, 185],
       [121, 163, 172, 142, 184],
       [172, 177, 136, 102, 137]])

In [36]:
b.ndim

2

In [37]:
df=pd.DataFrame(b,columns=['Roll','name','age','adds','country'],index=[182,183,185,186,187,188])
df

     Roll  name  age  adds  country
182   133   185  168   135      169
183   111   178  129   118      129
185   189   129  120   196      162
186   105   120  151   119      185
187   121   163  172   142      184
188   172   177  136   102      137

In [39]:
df.loc[187]

Roll       121
name       163
age        172
adds       142
country    184
Name: 187, dtype: int64

In [44]:
df.iloc[[1,3,4]]

     Roll  name  age  adds  country
183   111   178  129   118      129
186   105   120  151   119      185
187   121   163  172   142      184

In [45]:
df.age

182    168
183    129
185    120
186    151
187    172
188    136
Name: age, dtype: int64

In [46]:
df['age']

182    168
183    129
185    120
186    151
187    172
188    136
Name: age, dtype: int64

In [48]:
df[['adds','age']]

     adds  age
182   135  168
183   118  129
185   196  120
186   119  151
187   142  172
188   102  136

In [49]:
df.loc[[182,185,186],['adds','name','Roll']]

     adds  name  Roll
182   135   185   133
185   196   129   189
186   119   120   105

In [50]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [53]:
df1=sns.load_dataset('titanic')
df1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [54]:
type(df1)

pandas.core.frame.DataFrame

In [56]:
df.shape

(6, 5)

In [57]:
df1.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')